# This is a basic workflow to help you get started with Actions

name: testing out

on:
  push:
    branches: [main]

jobs:
  install-build:
    outputs:
      job-strategy-matrix: ${{ steps.install.outputs.job-strategy-matrix }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: install
        id: install
        run: |
          echo pnpm install
          node ./gen-service-version.js

  build-services:
    needs: [install-build]
    runs-on: ubuntu-latest
    if: ${{ needs.install-build.outputs.job-strategy-matrix != '[""]' }}
    strategy:
      matrix:
        service: ${{ fromJson(needs.install-build.outputs.job-strategy-matrix) }}
    steps:
      - name: Checkout code
        uses: gogaille/sparse-checkout@3114de9b3cf84c0829fe84222d8ae8d806fbc794
        with:
          patterns: '${{ matrix.service }} gen-service-version.js'

      - name: Build
        run: |
          ls .
          ./${{ matrix.service }}/build.sh
